version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-fleet
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleet_monitor
    ports:
      - "5480:5432"
    volumes:
      - postgresfadel:/var/lib/postgresql/data

volumes:
  postgresfadel:
    name: postgresfadel
